# .streamlit/secrets.toml
dialect = "postgresql"
host = "aws-0-ap-southeast-1.pooler.supabase.com"
port = 5432
database = "postgres"
username = "postgres.tpjulzqgzpimpwwsjivk"
password = "informatika2026"
# query = { charset = "xxx" }

